import { Artifact } from './types';

export const artifacts: Artifact[] = [
  {
    id: '1',
    no: '01',
    code: 'BRD-00001',
    name: 'BRD - Return orders as broken when delivery for Shopee',
    type: 'Business Requirement',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'In Progress',
    level: 0,
    startDate: '2023-10-01',
    dueDate: '2023-10-05',
    estimation: 8,
    priority: 'High',
  },
  {
    id: '2',
    no: '02',
    code: 'IMP-00001',
    name: 'Implementation Plan - Return orders as broken when delivery for Shopee',
    type: 'Implementation Plan',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'In Progress',
    level: 1,
    startDate: '2023-10-06',
    dueDate: '2023-10-10',
    estimation: 16,
    priority: 'High',
  },
  {
    id: '3',
    no: '03',
    code: 'FUN-00001',
    name: 'Function - Get to-be-returned orders from Shoppee',
    type: 'Implementation Function',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'In Progress',
    level: 2,
    startDate: '2023-10-11',
    dueDate: '2023-10-15',
    estimation: 24,
    priority: 'Medium',
  },
  {
    id: '4',
    no: '04',
    code: 'END-00001',
    name: 'Endpoint - Get returned orders from Shopee',
    type: 'Endpoint',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'In Progress',
    level: 3,
    startDate: '2023-10-16',
    dueDate: '2023-10-18',
    estimation: 12,
    priority: 'Medium',
  },
  {
    id: '5',
    no: '05',
    code: 'ENT-00001',
    name: 'Entity - returned_orders_shopee',
    type: 'Database Table',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'Done',
    level: 3,
    startDate: '2023-10-12',
    dueDate: '2023-10-14',
    estimation: 8,
    priority: 'High',
  },
  {
    id: '6',
    no: '06',
    code: 'ENT-00002',
    name: 'Entity - standard_orders',
    type: 'Database Table',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'Done',
    level: 3,
    startDate: '2023-10-12',
    dueDate: '2023-10-14',
    estimation: 8,
    priority: 'High',
  },
  {
    id: '7',
    no: '07',
    code: 'FUN-00002',
    name: 'Function - Configure mapping status',
    type: 'Implementation Function',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'In Progress',
    level: 2,
    startDate: '2023-10-19',
    dueDate: '2023-10-22',
    estimation: 16,
    priority: 'Medium',
  },
  {
    id: '8',
    no: '08',
    code: 'FUN-00003',
    name: 'Function - Transform orders from Shopee format to standard format',
    type: 'Implementation Function',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'In Progress',
    level: 2,
    startDate: '2023-10-23',
    dueDate: '2023-10-26',
    estimation: 20,
    priority: 'Medium',
  },
  {
    id: '9',
    no: '09',
    code: 'TES-00001',
    name: 'Testing - Return orders as broken when delivery for Shopee',
    type: 'Testing Ticket',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'In Progress',
    level: 1,
    startDate: '2023-10-27',
    dueDate: '2023-11-05',
    estimation: 40,
    priority: 'High',
  },
  {
    id: '10',
    no: '10',
    code: 'SCO-00001',
    name: 'Verify API-00001 endpoint',
    type: 'Scope',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'In Progress',
    level: 2,
    startDate: '2023-10-27',
    dueDate: '2023-10-29',
    estimation: 8,
    priority: 'Medium',
  },
  {
    id: '11',
    no: '11',
    code: 'CHE-00001',
    name: 'Verify API-00001 endpoint to handle successfully',
    type: 'Checklist',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'In Progress',
    level: 2,
    startDate: '2023-10-30',
    dueDate: '2023-11-01',
    estimation: 12,
    priority: 'Medium',
  },
  {
    id: '12',
    no: '12',
    code: 'CAS-00001',
    name: 'Verify API-00001 endpoint to handle returning order successfully from Shopee',
    type: 'Test Case',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'In Progress',
    level: 2,
    startDate: '2023-11-02',
    dueDate: '2023-11-05',
    estimation: 16,
    priority: 'High',
  },
  {
    id: '13',
    no: '13',
    code: 'STE-00001',
    name: 'Send an order return request to API-00001 webhook',
    type: 'Test Step',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'Done',
    level: 3,
    startDate: '2023-11-02',
    dueDate: '2023-11-02',
    estimation: 4,
    priority: 'Medium',
  },
  {
    id: '14',
    no: '14',
    code: 'STE-00002',
    name: 'Verify HTTP status in api response',
    type: 'Test Step',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'Done',
    level: 3,
    startDate: '2023-11-02',
    dueDate: '2023-11-02',
    estimation: 2,
    priority: 'Medium',
  },
  {
    id: '15',
    no: '15',
    code: 'STE-00003',
    name: 'Verify returning number',
    type: 'Test Step',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'Done',
    level: 3,
    startDate: '2023-11-03',
    dueDate: '2023-11-03',
    estimation: 2,
    priority: 'Medium',
  },
  {
    id: '16',
    no: '16',
    code: 'CAS-00002',
    name: 'Verify table TAB-00001 to have to return number inserted',
    type: 'Test Case',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'Not Started',
    level: 2,
    startDate: '2023-11-06',
    dueDate: '2023-11-08',
    estimation: 12,
    priority: 'Low',
  },
  {
    id: '17',
    no: '17',
    code: 'STE-00004',
    name: 'Verify order number to match with order no in request payload',
    type: 'Test Step',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'Not Started',
    level: 3,
    startDate: '2023-11-06',
    dueDate: '2023-11-06',
    estimation: 4,
    priority: 'Low',
  },
  {
    id: '18',
    no: '18',
    code: 'STE-00005',
    name: 'Verify return id to match with return id in api response',
    type: 'Test Step',
    assignee: 'Nguyễn Minh An',
    approvalStatus: 'APPROVED',
    implementationStatus: 'Not Started',
    level: 3,
    startDate: '2023-11-07',
    dueDate: '2023-11-07',
    estimation: 4,
    priority: 'Low',
  },
];
